name: ExifImageRenamer

on:
    push:
        branches:
            - main

env:
    ENV: prod

jobs:
    Deploy:
        name: Run on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                # os: [ubuntu-latest]
                os: [ ubuntu-latest, macOS-latest, windows-latest ]

            # - name: Agent Info
            #   run: ./.github/scripts/AgentInfo.sh
            # - name: Install Tools
            #   run: ./InstallTools.sh



        steps:
            - name: checking out the git repo
              uses: actions/checkout@master


            - name: Python Info
              run: |
                echo "\n------------------------\nPython version\n------------------------"
                python --version
                echo "\n------------------------\nPython3 version\n------------------------"
                python3 --version
            # - name: Agent Info
            #   run: ./.github/scripts/AgentInfo.sh
            # - name: Install Tools
            #   run: ./InstallTools.sh


            - name: Run unit tests (Linux only)
              if: contains(matrix.os, 'ubuntu')
              run: |
                  export PATH=/home/runner/.local/bin:$PATH
                  make install_dev
                  make coverage
            - name: Run tests (MacOS-only)
              if: contains(matrix.os, 'macOS')
              run: |
                export PATH=/Users/runner/Library/Python/3.9/bin:$PATH
                make install_dev3
                make test3
            - name: Run unit tests (windows-only)
              if: contains(matrix.os, 'windows')
              run: |
                set PATH="%PATH%;C:\Users\runneradmin\AppData\Roaming\Python\Python37\Scripts"
                make install_dev
                make test
