name: ExifImageRenamer

on:
    push:
        branches:
            - main

env:
    ENV: prod

jobs:
    Deploy:
        name: Run on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                # os: [ubuntu-latest]
                os: [ ubuntu-latest, macOS-latest, windows-latest ]

            # - name: Agent Info
            #   run: ./.github/scripts/AgentInfo.sh
            # - name: Install Tools
            #   run: ./InstallTools.sh



        steps:
            # - name: checking out the git repo
            #   uses: actions/checkout@master
            - name: checkout repo
              uses: actions/checkout@v2
            - name: setup python
              uses: actions/setup-python@v2
              with:
                python-version: 3.8


            - name: Python Info
              run: |
                echo ""
                echo "------------------------"
                echo "Python version"
                echo "------------------------"
                python --version
                echo ""
                echo "------------------------"
                echo "Python3 version"
                echo "------------------------"
                python3 --version
            # - name: Agent Info
            #   run: ./.github/scripts/AgentInfo.sh
            # - name: Install Tools
            #   run: ./InstallTools.sh

            # - name: run with python 3.8.9
            #   uses: ./
            #   with:
            #     python-version: 3.8.9
            - name: install dependencies
              run: make install_github_dev
            - name: run unit tests
              run: make test_ff
            - name: run coverage
              run: make coverage



            # - name: Run unit tests (Linux only)
            #   if: contains(matrix.os, 'ubuntu')
            #   shell: bash
            #   run: |
            #     echo "*********** add to the path *************"
            #     # export PATH=/home/runner/.local/bin:$PATH
            #     echo "/home/runner/.local/bin" >> $GITHUB_PATH
            #     echo "*********** make install_dev *************"
            #     make install_dev
            #     echo "*********** make coverage *************"
            #     make coverage
            # - name: Run tests (MacOS-only)
            #   if: contains(matrix.os, 'macOS')
            #   shell: bash
            #   run: |
            #     echo "*********** add to the path *************"
            #     export PATH=/Users/runner/Library/Python/3.9/bin:$PATH
            #     # echo "/Users/runner/Library/Python/3.9/bin" >> $GITHUB_PATH
            #     echo "*********** make install_dev3 *************"
            #     make install_dev3
            #     echo "*********** make test *************"
            #     make test3
            #     echo "*********** make coverage *************"
            #     make coverage
            # - name: Run unit tests (windows-only)
            #   if: contains(matrix.os, 'windows')
            #   shell: pwsh
            #   run: |
            #     echo "*********** MAGICK_HOME *************"
            #     # $env:MAGICK_HOME = "C:\Users\runneradmin\AppData\Roaming\Python\Python37\Scripts"
            #     echo "*********** add to the path *************"
            #     $env:Path += ";C:\Users\runneradmin\AppData\Roaming\Python\Python37\Scripts"
            #     # echo "C:\Users\runneradmin\AppData\Roaming\Python\Python37\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
            #     # echo "*********** display GITHUB_PATH *************"
            #     # echo ${env:GITHUB_PATH}
            #     # echo "*********** display PATH *************"
            #     # echo ${env:PATH}
            #     echo "*********** abk install_dev_win *************"
            #     make install_dev
            #     echo "*********** abk test *************"
            #     make test
