name: ExifImageRenamer

on:
    push:
        branches:
            - main

env:
    ENV: prod

jobs:
    Deploy:
        name: Run on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                # os: [ubuntu-latest]
                os: [ ubuntu-latest, macOS-latest, windows-latest ]

            # - name: Agent Info
            #   run: ./.github/scripts/AgentInfo.sh
            # - name: Install Tools
            #   run: ./InstallTools.sh



        steps:
            - name: checking out the git repo
              uses: actions/checkout@master


            - name: Python Info
              run: |
                echo ""
                echo "------------------------"
                echo "Python version"
                echo "------------------------"
                python --version
                echo ""
                echo "------------------------"
                echo "Python3 version"
                echo "------------------------"
                python3 --version
            # - name: Agent Info
            #   run: ./.github/scripts/AgentInfo.sh
            # - name: Install Tools
            #   run: ./InstallTools.sh


            - name: Run unit tests (Linux only)
              if: contains(matrix.os, 'ubuntu')
              run: |
                  export PATH=/home/runner/.local/bin:$PATH
                  make install_dev
                  make coverage
            - name: Run tests (MacOS-only)
              if: contains(matrix.os, 'macOS')
              run: |
                export PATH=/Users/runner/Library/Python/3.9/bin:$PATH
                make install_dev3
                make test3
            - name: Run unit tests (windows-only)
              if: contains(matrix.os, 'windows')
              run: |
                echo "*********** abk PATH *************"
                echo "C:\Users\runneradmin\AppData\Roaming\Python\Python37\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
                echo %GITHUB_PATH%
                echo "*********** abk install_dev_win *************"
                make install_dev_win
                echo "*********** abk test *************"
                make test
